config/routes.rb
Rails.application.routes.draw do
  resources :sites
  get 'scrape'=> 'scrape#index'
  get 'scrape/test'=> 'scrape#test'
  root 'sites#index'

end

app/models/site.rb
class Site < ActiveRecord::Base
  validates_uniqueness_of :name
  validates_uniqueness_of :base_url
  
  validates :name, presence: true
  validates :base_url, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/scrape_controller.rb
require 'scraper'

class ScrapeController < ApplicationController
  respond_to :html, :xml, :json
  def index
    respond_with
  end

  def test
    url = params.fetch(:url)
    render json: JSON.pretty_generate(Scraper.instance.extract_properties(url))
  end
end

app/controllers/sites_controller.rb
require 'scraper'

class SitesController < ApplicationController
  respond_to :html, :xml, :json

  def index
    @sites = Site.all
    respond_with @sites
  end

  def new
    @site = Site.new
    respond_with @site
  end

  def edit
    @site = Site.find(params[:id])
    respond_with @site
  end

  def create
    Site.create!(site_params)
    flash[:notice] = "Site was created!"
    redirect_to sites_path
  end

  def update
    site = Site.find(params[:id])
    puts site_params[:rule]
    site.update!(site_params)

    flash[:notice] = "Site was saved!"
    redirect_to sites_path
  end

  def destroy
    Site.destroy(params[:id])
    flash[:notice] = "Site was deleted!"
    redirect_to sites_path
  end

  private
  def site_params
    site_params = params.require(:site).permit(:name, :base_url, :test_url, :rules)
    site_params[:base_url] = Scraper.instance.flatten_host(site_params[:base_url]) if site_params[:base_url]

    site_params
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sites_helper.rb
module SitesHelper
  def parse_rules(site)    
    JSON.parse(site.rules.present? ? site.rules : "{}")
  end

  def get_tester_url(site)
    scrape_test_path(url: site.test_url)
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Scrapy</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.min.css"/>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<nav class="navbar navbar-default" role="navigation">
	<div class="container-fluid">
    	<div class="navbar-header">
	      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
	        <span class="sr-only">Toggle navigation</span>
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	      </button>
	      <a class="navbar-brand" href="#">Scrapy</a>
	    </div>
	    <div id="navbar" class="collapse navbar-collapse">
	      <ul class="nav navbar-nav">
	        <li class="active"><a href="/sites">Sites</a></li>
	        <li><a href="/scrape">Scrape</a></li>
	      </ul>
	    </div><!--/.nav-collapse -->
  </div>
</nav>
 <div class="container">      
 	<% if(flash[:notice].present?) %>
		<div class="alert alert-success">
			<%= flash[:notice] %>
		</div>
	<% end %>
	<%= yield %>
</div>

<script src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/js/bootstrap.min.js"></script>
<!-- <script src="http://ajax.aspnetcdn.com/ajax/jquery.validate/1.13.1/jquery.validate.min.js"></script> -->
<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
</body>
</html>

app/views/scrape/index.html.slim
form role="form"
  .form_group
    label for="urlText" Enter Url:
    input#urlText.form-control type="text"
  p.clearfix
  p.clearfix
    button#scrape_url.btn.btn-success type="button" Scrape

app/views/sites/_edit_site.html.slim
= form_for @site, role: 'form', html: {class: 'upsert_site'} do |f|
  .form_group
    = f.label :name
    = f.text_field :name, class: 'form-control', required: true, autofocus: true
  .form_group
    = f.label :base_url
    = f.text_field :base_url, class: 'form-control', required: true
  .form_group
    = f.label :test_url
    = f.text_field :test_url, class: 'form-control'
  .form_group
    label for="add_rule" Site Rules:
    p.clearfix
      button#add_rule.btn.btn-success type="button" Add Rule
    p.clearfix
      div#rules_container.list-group
        - for prop,config in parse_rules(@site) do
          .list-group-item.rules_list
            span.glyphicon.glyphicon-remove.pull-right.remove_site_rule aria-hidden="true" data-prop-name="#{prop}"
            h4.list-group-item-heading = prop
            p.list-group-item-text Rule: #{config['rule']}
            p.list-group-item-text Attribute: #{config['attribute']}

  = f.hidden_field(:rules)

  br.clearfix
  = f.submit 'Save', class: "button btn btn-primary"
       
.modal.fade#ruleModal tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel" aria-hidden="true"
  .modal-dialog
    .modal-content
      .modal-header
        h4.modal-title Add New Rule
      .modal-body
        .container-fluid
          form#addRuleForm role="form"
            .form-group
              label for="propName" Property Name:
              input#propName.form-control type="text" required="true"
            .form-group
              label for="propRule" Rule(CSS syntax):
              input#propRule.form-control type="text" required="true"
            .form-group
              label for="propAttr" DOM Attribute:
              input#propAttr.form-control placeholder="Leave empty for tag text" type="text" 
            button#submitAddRule type="submit" style="display:none"
          .modal-footer
            button.btn.btn-default type="button" data-toggle="modal" data-target=".bs-example-modal-sm" data-dismiss="modal" Close
            button.btn.btn-success#saveRule type="button" data-toggle="modal" data-target=".bs-example-modal-sm" Add

app/views/sites/edit.html.slim
h1 Edit Site
= render partial: 'edit_site'

app/views/sites/index.html.slim
table.table.sites
  thead
    tr
      td Id
      td Name
      td Base Url
      td Actions
  - for site in @sites do
    tr
      td = site.id
      td = site.name
      td = site.base_url
      td
        a.glyphicon.glyphicon-edit.pull-left aria-hidden="true" title="edit" href="#{edit_site_path(site)}"
        = link_to "", site, method: 'delete', data: { confirm: "Do you want to delete #{site.name}?" }, class: "glyphicon glyphicon-remove pull-left"
        - if site.test_url.present?
          a.glyphicon.glyphicon-play.pull-left aria-hidden="true" target="_blank" title="test" href="#{get_tester_url(site)}"



a#add_rule.btn.btn-success type="button" href="#{new_site_path}" New Site

app/views/sites/new.html.slim
h1 New Site
= render partial: 'edit_site'